spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: changeme
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level :
    org.hibernate.SQL: DEBUG
    hibernate.type.descriptor.sql.BasicBinder: TRACE
