spring:
  datasource:
    auto-commit: false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: changeme
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: TRACE
    hibernate.type.descriptor.sql.BasicBinder: TRACE
