server.port: 9000

spring:
  datasource:
    username: postgres
    password: changeme
    url: jdbc:postgresql://localhost:5432/demo

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      springframework.transaction: TRACE
    hibernate.type.descriptor.BasicBinder: TRACE